import accountRoutes from './accountRoutes'
import announcementMsgRoutes from './announcementMsgRoutes'
import basisMsgRoutes from './basisMsgRoutes'
import homeRoutes from './homeRoutes'
import logRoutes from './logRoutes'
import projActiveRoutes from './projActiveRoutes'
import projAuditRoutes from './projAuditRoutes'
import projMsgRoutes from './projMsgRoutes'
import projReviewRoutes from './projReviewRoutes'
import teacherMsgRoutes from './teacherMsgRoutes'
import otherRoutes from './otherRoutes'

export { accountRoutes }
export { announcementMsgRoutes }
export { basisMsgRoutes }
export { homeRoutes }
export { logRoutes }
export { projActiveRoutes }
export { projAuditRoutes }
export { projMsgRoutes }
export { projReviewRoutes }
export { teacherMsgRoutes }
export { otherRoutes }
